export const MOCK_USERS = [
  {
    id: '1',
    firstName: 'Admin',
    lastName: 'Admin',
    email: 'admin@raf.rs',
    password: 'admin',
    permissions: [
      'is_admin',
      'create_user',
      'read_user',
      'update_user',
      'delete_user',
      'search_machine',
      'start_machine',
      'stop_machine',
      'restart_machine',
      'create_machine',
      'destroy_machine',
      'read_errors',
      'read_schedules',
    ],
  },
  {
    id: '2',
    firstName: 'Pera',
    lastName: 'Peric',
    email: 'pera@raf.rs',
    password: 'pera',
    permissions: ['read_user'],
  },
  {
    id: '3',
    firstName: 'Zika',
    lastName: 'Zikic',
    email: 'zika@raf.rs',
    password: 'zika',
    permissions: ['read_user', 'search_machine', 'start_machine'],
  },
];

export const MOCK_MACHINES = [
  {
    id: '1',
    name: 'Masina admina',
    type: 'server',
    description: 'serverska masina',
    state: 'UGASENA',
    createdBy: '1',
    active: true,
    createdAt: new Date('2025-11-01'),
    schedule: {
      date: '2025-12-01',
      time: '10:00',
      operation: 'UPALI',
    },
  },
  {
    id: '2',
    name: 'Masina zike',
    type: 'baza',
    description: 'baza podataka',
    state: 'UPALJENA',
    createdBy: '3',
    active: true,
    createdAt: new Date('2025-11-05'),
  },
  {
    id: '3',
    name: 'Masina druga zike',
    type: 'test',
    description: 'test masina',
    state: 'UGASENA',
    createdBy: '3',
    active: true,
    createdAt: new Date('2025-11-07'),
  },
];

export const MACHINE_ERROR_LOGS = [
  {
    id: '1',
    machineId: '1',
    operation: 'UPALI',
    message: 'Mašina nije bila UGASENA.',
    date: new Date('2025-11-08T10:30:00'),
    createdBy: '1',
  },
  {
    id: '2',
    machineId: '3',
    operation: 'RESTARTUJ',
    message: 'Mašina nije bila UPALJENA.',
    date: new Date('2025-11-08T11:15:00'),
    createdBy: '3',
  },
  {
    id: '3',
    machineId: '2',
    operation: 'UGASI',
    message: 'Mašina nije bila UPALJENA.',
    date: new Date('2025-09-08T11:15:00'),
    createdBy: '1',
  },
];
